name: Docker Image CI

on:
  push:
    tags:
    - "*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t jbkerry/oligo:latest -t jbkerry/oligo:${{ github.ref_name }}
